spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emr_xml?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapping/*/*.xml